# Generated by Django 4.1.4 on 2023-01-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='des',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ways',
            name='way',
            field=models.JSONField(),
        ),
    ]
